<a href="https://colab.research.google.com/github/onewithano/MLprojectsplacement/blob/main/machine_learning_using_projects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# movie recommendation app

In [24]:
import numpy as np
import pandas as pd
from google.colab import files
data = files.upload()

Saving tmdb_5000_credits.csv to tmdb_5000_credits (1).csv
Saving tmdb_5000_movies.csv to tmdb_5000_movies (1).csv

In [25]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [26]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [27]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [28]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [29]:
 movies = movies.merge(credits,on='title')

In [30]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [31]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [60]:
 movies = movies[[ 'title','overview','genres','keywords','id',]]

In [61]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4806 entries, 0 to 4808
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     4806 non-null   object
 1   overview  4806 non-null   object
 2   genres    4778 non-null   object
 3   keywords  4806 non-null   object
 4   id        4806 non-null   int64
dtypes: int64(1), object(4)
memory usage: 225.3+ KB

In [62]:
movies.head(1)

,title,overview,genres,keywords,id
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",[Action],"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",19995

In [63]:
movies.head()

,title,overview,genres,keywords,id
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",[Action],"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",19995
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",[Adventure],"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",285
2,Spectre,A cryptic message from Bond’s past sends him o...,[Action],"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",206647
3,The Dark Knight Rises,Following the death of District Attorney Harve...,[Action],"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",49026
4,John Carter,"John Carter is a war-weary, former military ca...",[Action],"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",49529

In [93]:
movies.isnull().sum()

title       0
overview    0
genres      0
keywords    0
id          0
dtype: int64

In [94]:
movies.dropna(inplace=True)

In [95]:
movies.iloc[0].genres

['Action']

In [97]:
def convert (obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
    return L

In [98]:
movies['genres'].apply(convert)

ValueError: ignored